# Generated by Django 3.2 on 2021-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.CharField(blank=True, default='27-04-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='internattendance',
            name='date',
            field=models.CharField(blank=True, default='27-04-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.CharField(blank=True, default='27-04-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='traineeattendance',
            name='date',
            field=models.CharField(blank=True, default='27-04-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='date',
            field=models.CharField(blank=True, default='27-04-2021', max_length=100),
        ),
    ]
